// LOGIN REQUESTS
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';

// PLAYLISTS
export const PLAYLISTS_REQUEST = 'PLAYLISTS_REQUEST';
export const PLAYLISTS_REQUEST_SUCCESS = 'PLAYLISTS_REQUEST_SUCCESS';
export const PLAYLISTS_REQUEST_FAILED = 'PLAYLISTS_REQUEST_FAILED';

// TRACKS
export const TRACKS_REQUEST = 'TRACKS_REQUEST';
export const TRACKS_REQUEST_SUCCESS = 'TRACKS_REQUEST_SUCCESS';
export const TRACKS_REQUEST_FAILED = 'TRACKS_REQUEST_FAILED';

// ALBUM
export const ALBUM_REQUEST = 'ALBUM_REQUEST';
export const ALBUM_REQUEST_SUCCESS = 'ALBUM_REQUEST_SUCCESS';
export const ALBUM_REQUEST_FAILED = 'ALBUM_REQUEST_FAILED';
